
#pragma once

#define ERROR_PFX(NAME) ERROR_##NAME

typedef enum {
    ERROR_PFX(OK),
    ERROR_PFX(FILE_NOT_FOUND),
    ERROR_PFX(CANNOT_READ_FILE),
    ERROR_PFX(INVALID_TOKEN_FOUND),
    ERROR_PFX(MAX_TOKEN_LEN_EXCEEDED),
    ERROR_PFX(INVALID_BYTES_FOR_CHAR)
} var_error;
